#!/usr/bin/env bash

set -e

if ! docker ps | grep pagium-selenium-standalone > /dev/null; then
    docker run --name pagium-selenium-standalone -p 4444:4444 -d selenium/standalone-chrome-debug > /dev/null
    sleep 5
fi

cd $(readlink -f $(dirname ${0})) && pytest $@

docker rm -f pagium-selenium-standalone > /dev/null
