name: Check Python style

on: [push]

jobs:
  check_style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install flake8
      - name: check flake8
        run: |
          flake8 --ignore="E501" ./

  test:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome:3.141.59-20200525
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install selenium pyhamcrest -U
      - name: Wait for selenuim to start
        run: ./wait_for_selenium.sh
      - name: test
        run: |
          python -m doctest -v ./pagium/*.py

